//-----------------------------------------------------------------------
// <copyright file="DependencyInjectionSetupTests.cs" company="JDV Software Ltd">
//     Copyright (c) JDV Software Ltd. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

using Foundation.BusinessProcess.App;
using Foundation.BusinessProcess.Components;
using Foundation.BusinessProcess.Core;
using Foundation.BusinessProcess.Core.EnumProcesses;
using Foundation.BusinessProcess.Helpers;
using Foundation.BusinessProcess.Log;
using Foundation.BusinessProcess.Log.EnumProcesses;
using Foundation.BusinessProcess.Main;
using Foundation.BusinessProcess.Sec;
using Foundation.BusinessProcess.Sec.EnumProcesses;
using Foundation.BusinessProcess.Stg;

using Foundation.Core;
using Foundation.Common;
using Foundation.DataAccess.Database;
using Foundation.DocumentGenerator;
using Foundation.Interfaces;

using Foundation.Models.App;
using Foundation.Models.Core;
using Foundation.Models.Core.EnumModels;
using Foundation.Models.Log;
using Foundation.Models.Log.EnumModels;
using Foundation.Models.Sec;
using Foundation.Models.Sec.EnumModels;
using Foundation.Models.Specialised;
using Foundation.Models.Stg;

using Foundation.Repository.App;
using Foundation.Repository.Core;
using Foundation.Repository.Core.EnumRepositories;
using Foundation.Repository.DataProvider;
using Foundation.Repository.Log;
using Foundation.Repository.Log.EnumRepositories;
using Foundation.Repository.Sec;
using Foundation.Repository.Sec.EnumRepositories;
using Foundation.Repository.Specialised;
using Foundation.Repository.Stg;
using Foundation.Security;
using Foundation.Service;
using Foundation.Services.Application;
using Foundation.Services.FileIdentification;
using Foundation.Services.Mail;
using Foundation.Services.Mail.Services;
using Foundation.Services.MessageQueue;
using Foundation.Services.UserInteraction;
using Foundation.Services.WebApi;

using Foundation.Views;

using Foundation.ViewModels.App;
using Foundation.ViewModels.Core;
using Foundation.ViewModels.Core.EnumViewModels;
using Foundation.ViewModels.Log;
using Foundation.ViewModels.Log.EnumViewModels;
using Foundation.ViewModels.Sec;
using Foundation.ViewModels.Sec.EnumViewModels;
using Foundation.ViewModels.Services;
using Foundation.ViewModels.Stg;

using Foundation.Tests.Unit.Mocks;
using Foundation.Tests.Unit.Support;
using Foundation.ViewModels.Test;
using Foundation.WorkflowEngine;

namespace Foundation.Tests.Unit.Foundation.Core
{
    /// <summary>
    /// The DependencyInjectionSetupTests
    /// </summary>
    public class DependencyInjectionSetupTests // Do not inherit from UnitTestBase
    {
        [TestCase]
        public void Test_Direct()
        {
            HostApplicationBuilderSettings settings = new HostApplicationBuilderSettings();
            HostApplicationBuilder hostApplicationBuilder = Host.CreateApplicationBuilder(settings);

            hostApplicationBuilder.Services.AddTransient(typeof(IMenuItem), typeof(MenuItem));

            hostApplicationBuilder.Services.AddTransient(typeof(IMultipleInstances), typeof(MultipleInstance1));
            hostApplicationBuilder.Services.AddTransient(typeof(IInstance1), typeof(MultipleInstance1));

            hostApplicationBuilder.Services.AddTransient(typeof(IMultipleInstances), typeof(MultipleInstance2));
            hostApplicationBuilder.Services.AddTransient(typeof(IInstance2), typeof(MultipleInstance2));

            hostApplicationBuilder.Services.AddTransient(typeof(ITransientOperation), typeof(TransientOperation));

            IHost theHost = hostApplicationBuilder.Build();

            IMenuItem menuItem = theHost.Services.GetService<IMenuItem>()!;
            Assert.That(menuItem, Is.Not.Null);

            List<IMultipleInstances>? multipleInstances = theHost.Services.GetServices<IMultipleInstances>().ToList();
            Assert.That(multipleInstances, Is.Not.Null);
            Assert.That(multipleInstances?.Count(), Is.EqualTo(2));

            IInstance1 instance1 = theHost.Services.GetService<IInstance1>()!;
            Assert.That(instance1, Is.Not.Null);

            IInstance2 instance2 = theHost.Services.GetService<IInstance2>()!;
            Assert.That(instance2, Is.Not.Null);

            ITransientOperation transientOperation = theHost.Services.GetService<ITransientOperation>()!;
            Assert.That(transientOperation, Is.Not.Null);
        }

        [TestCase]
        public void Test_Foundation()
        {
            HostApplicationBuilderSettings settings = new HostApplicationBuilderSettings();
            HostApplicationBuilder hostApplicationBuilder = Host.CreateApplicationBuilder(settings);

            DependencyInjectionSetup.ResetDependencyInjection();
            
            DependencyInjectionSetup.SetupDependencyInjection(hostApplicationBuilder.Services, "*", "*.dll");
            //SetupDI(hostApplicationBuilder);

            IHost theHost = hostApplicationBuilder.Build();

            IMenuItem? menuItem = theHost.Services.GetService<IMenuItem>();
            Assert.That(menuItem, Is.Not.Null);

            IInstance1? instance1 = theHost.Services.GetService<IInstance1>();
            Assert.That(instance1, Is.Not.Null);

            List<IMultipleInstances>? multipleInstances = theHost.Services.GetServices<IMultipleInstances>().ToList();
            Assert.That(multipleInstances, Is.Not.Null);
            Assert.That(multipleInstances?.Count(), Is.EqualTo(2));
        }
        private void SetupDI(HostApplicationBuilder hostApplicationBuilder)
        {
            hostApplicationBuilder.Services.AddSingleton(typeof(ApplicationWrapper));
            hostApplicationBuilder.Services.AddSingleton(typeof(IApplicationWrapper), typeof(ApplicationWrapper));
            hostApplicationBuilder.Services.AddSingleton(typeof(Cache));
            hostApplicationBuilder.Services.AddSingleton(typeof(ICache), typeof(Cache));
            hostApplicationBuilder.Services.AddSingleton(typeof(ClipBoardWrapper));
            hostApplicationBuilder.Services.AddSingleton(typeof(IClipBoardWrapper), typeof(ClipBoardWrapper));
            hostApplicationBuilder.Services.AddSingleton(typeof(global::Foundation.Core.Core));
            hostApplicationBuilder.Services.AddSingleton(typeof(ICore), typeof(global::Foundation.Core.Core));
            hostApplicationBuilder.Services.AddSingleton(typeof(Crypto));
            hostApplicationBuilder.Services.AddSingleton(typeof(ICrypto), typeof(Crypto));
            hostApplicationBuilder.Services.AddSingleton(typeof(DispatcherTimerWrapper));
            hostApplicationBuilder.Services.AddSingleton(typeof(IDispatcherTimerWrapper), typeof(DispatcherTimerWrapper));
            hostApplicationBuilder.Services.AddSingleton(typeof(DispatcherWrapper));
            hostApplicationBuilder.Services.AddSingleton(typeof(IDispatcherWrapper), typeof(DispatcherWrapper));
            hostApplicationBuilder.Services.AddSingleton(typeof(LoggingHelpers));
            hostApplicationBuilder.Services.AddSingleton(typeof(IApplicationStartup), typeof(LoggingHelpers));
            hostApplicationBuilder.Services.AddSingleton(typeof(MockApplicationStartup));
            hostApplicationBuilder.Services.AddSingleton(typeof(IMockApplicationStartup), typeof(MockApplicationStartup));
            hostApplicationBuilder.Services.AddSingleton(typeof(MockApplicationStartup));
            hostApplicationBuilder.Services.AddSingleton(typeof(IApplicationStartup), typeof(MockApplicationStartup));
            hostApplicationBuilder.Services.AddSingleton(typeof(MouseWrapper));
            hostApplicationBuilder.Services.AddSingleton(typeof(IMouseWrapper), typeof(MouseWrapper));
            hostApplicationBuilder.Services.AddSingleton(typeof(SharedVariables));
            hostApplicationBuilder.Services.AddSingleton(typeof(ISharedVariables), typeof(SharedVariables));
            hostApplicationBuilder.Services.AddSingleton(typeof(WindowWrapper));
            hostApplicationBuilder.Services.AddSingleton(typeof(IWindowWrapper), typeof(WindowWrapper));
            hostApplicationBuilder.Services.AddSingleton(typeof(WpfApplicationObjects));
            hostApplicationBuilder.Services.AddSingleton(typeof(IWpfApplicationObjects), typeof(WpfApplicationObjects));
            hostApplicationBuilder.Services.AddScoped(typeof(StandardClass));
            hostApplicationBuilder.Services.AddScoped(typeof(IStandardClass), typeof(StandardClass));
            hostApplicationBuilder.Services.AddTransient(typeof(ActiveDirectoryUser));
            hostApplicationBuilder.Services.AddTransient(typeof(IActiveDirectoryUser), typeof(ActiveDirectoryUser));
            hostApplicationBuilder.Services.AddTransient(typeof(ActiveDirectoryUserProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IActiveDirectoryUserProcess), typeof(ActiveDirectoryUserProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ActiveDirectoryUserRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IActiveDirectoryDataAccess), typeof(ActiveDirectoryUserRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ActiveDirectoryUserViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IActiveDirectoryUserViewModel), typeof(ActiveDirectoryUserViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(Application));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplication), typeof(Application));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationApplicationType));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationApplicationType), typeof(ApplicationApplicationType));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationApplicationTypeProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationApplicationTypeProcess), typeof(ApplicationApplicationTypeProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationApplicationTypeRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationApplicationTypeDataAccess), typeof(ApplicationApplicationTypeRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationApplicationTypeViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationApplicationTypeViewModel), typeof(ApplicationApplicationTypeViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationConfiguration));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationConfiguration), typeof(ApplicationConfiguration));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationConfigurationProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationConfigurationProcess), typeof(ApplicationConfigurationProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationConfigurationRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationConfigurationRepository), typeof(ApplicationConfigurationRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationConfigurationService));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationConfigurationService), typeof(ApplicationConfigurationService));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationConfigurationViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationConfigurationViewModel), typeof(ApplicationConfigurationViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationProcess), typeof(ApplicationProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationDataAccess), typeof(ApplicationRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(global::Foundation.Models.Sec.EnumModels.ApplicationRole));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationRole), typeof(global::Foundation.Models.Sec.EnumModels.ApplicationRole));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationRoleProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationRoleProcess), typeof(ApplicationRoleProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationRoleRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationRoleDataAccess), typeof(ApplicationRoleRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationRoleViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationRoleViewModel), typeof(ApplicationRoleViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationType));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationType), typeof(ApplicationType));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationTypeProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationTypeProcess), typeof(ApplicationTypeProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationTypeRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationTypeDataAccess), typeof(ApplicationTypeRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationTypeViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationTypeViewModel), typeof(ApplicationTypeViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationUserRole));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationUserRole), typeof(ApplicationUserRole));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationUserRoleProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationUserRoleProcess), typeof(ApplicationUserRoleProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationUserRoleRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationUserRoleDataAccess), typeof(ApplicationUserRoleRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationUserRoleViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationUserRoleViewModel), typeof(ApplicationUserRoleViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ApplicationViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IApplicationViewModel), typeof(ApplicationViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(global::Foundation.Models.Core.EnumModels.ApprovalStatus));
            hostApplicationBuilder.Services.AddTransient(typeof(IApprovalStatus), typeof(global::Foundation.Models.Core.EnumModels.ApprovalStatus));
            hostApplicationBuilder.Services.AddTransient(typeof(ApprovalStatusProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IApprovalStatusProcess), typeof(ApprovalStatusProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ApprovalStatusRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IApprovalStatusRepository), typeof(ApprovalStatusRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ApprovalStatusViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IApprovalStatusViewModel), typeof(ApprovalStatusViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ArchiveTransferSettings));
            hostApplicationBuilder.Services.AddTransient(typeof(IArchiveTransferSettings), typeof(ArchiveTransferSettings));
            hostApplicationBuilder.Services.AddTransient(typeof(AuthenticationProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IAuthenticationProcess), typeof(AuthenticationProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(AuthenticationTokenRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IAuthenticationDataAccess), typeof(AuthenticationTokenRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(AuthorisationProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IAuthorisationProcess), typeof(AuthorisationProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(BasicControlsViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IBasicControlsViewModel), typeof(BasicControlsViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(CalendarRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ICalendarRepository), typeof(CalendarRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(CalendarService));
            hostApplicationBuilder.Services.AddTransient(typeof(ICalendarService), typeof(CalendarService));
            hostApplicationBuilder.Services.AddTransient(typeof(CommandParser));
            hostApplicationBuilder.Services.AddTransient(typeof(ICommandParser), typeof(CommandParser));
            hostApplicationBuilder.Services.AddTransient(typeof(global::Foundation.Models.Core.EnumModels.ConfigurationScope));
            hostApplicationBuilder.Services.AddTransient(typeof(IConfigurationScope), typeof(global::Foundation.Models.Core.EnumModels.ConfigurationScope));
            hostApplicationBuilder.Services.AddTransient(typeof(ConfigurationScopeProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IConfigurationScopeProcess), typeof(ConfigurationScopeProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ConfigurationScopeRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IConfigurationScopeRepository), typeof(ConfigurationScopeRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ConfigurationScopeViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IConfigurationScopeViewModel), typeof(ConfigurationScopeViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ContactDetail));
            hostApplicationBuilder.Services.AddTransient(typeof(IContactDetail), typeof(ContactDetail));
            hostApplicationBuilder.Services.AddTransient(typeof(ContactDetailProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IContactDetailProcess), typeof(ContactDetailProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ContactDetailRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IContactDetailRepository), typeof(ContactDetailRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ContactDetailViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IContactDetailViewModel), typeof(ContactDetailViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ContactType));
            hostApplicationBuilder.Services.AddTransient(typeof(IContactType), typeof(ContactType));
            hostApplicationBuilder.Services.AddTransient(typeof(ContactTypeProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IContactTypeProcess), typeof(ContactTypeProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ContactTypeRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IContactTypeRepository), typeof(ContactTypeRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ContactTypeViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IContactTypeViewModel), typeof(ContactTypeViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(Contract));
            hostApplicationBuilder.Services.AddTransient(typeof(IContract), typeof(Contract));
            hostApplicationBuilder.Services.AddTransient(typeof(ContractProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IContractProcess), typeof(ContractProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ContractRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IContractRepository), typeof(ContractRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ContractType));
            hostApplicationBuilder.Services.AddTransient(typeof(IContractType), typeof(ContractType));
            hostApplicationBuilder.Services.AddTransient(typeof(ContractTypeProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IContractTypeProcess), typeof(ContractTypeProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ContractTypeRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IContractTypeRepository), typeof(ContractTypeRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ContractTypeViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IContractTypeViewModel), typeof(ContractTypeViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ContractViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IContractViewModel), typeof(ContractViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(CoreDataProvider));
            hostApplicationBuilder.Services.AddTransient(typeof(ICoreDataProvider), typeof(CoreDataProvider));
            hostApplicationBuilder.Services.AddTransient(typeof(Country));
            hostApplicationBuilder.Services.AddTransient(typeof(ICountry), typeof(Country));
            hostApplicationBuilder.Services.AddTransient(typeof(CountryProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ICountryProcess), typeof(CountryProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(CountryRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ICountryRepository), typeof(CountryRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(CountryViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ICountryViewModel), typeof(CountryViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(CrossSiteScriptingIdentifier));
            hostApplicationBuilder.Services.AddTransient(typeof(ICrossSiteScriptingIdentifier), typeof(CrossSiteScriptingIdentifier));
            hostApplicationBuilder.Services.AddTransient(typeof(CrossSiteScriptingIdentifier));
            hostApplicationBuilder.Services.AddTransient(typeof(IInjectionIdentifier), typeof(CrossSiteScriptingIdentifier));
            hostApplicationBuilder.Services.AddTransient(typeof(Currency));
            hostApplicationBuilder.Services.AddTransient(typeof(ICurrency), typeof(Currency));
            hostApplicationBuilder.Services.AddTransient(typeof(CurrencyProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ICurrencyProcess), typeof(CurrencyProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(CurrencyRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ICurrencyRepository), typeof(CurrencyRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(CurrencyViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ICurrencyViewModel), typeof(CurrencyViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(DatabaseParameters));
            hostApplicationBuilder.Services.AddTransient(typeof(IDatabaseParameters), typeof(DatabaseParameters));
            hostApplicationBuilder.Services.AddTransient(typeof(DatabaseSchemaColumn));
            hostApplicationBuilder.Services.AddTransient(typeof(IDatabaseSchemaColumn), typeof(DatabaseSchemaColumn));
            hostApplicationBuilder.Services.AddTransient(typeof(DatabaseSchemaColumnRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IDatabaseSchemaColumnDataAccess), typeof(DatabaseSchemaColumnRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(DatabaseSchemaTable));
            hostApplicationBuilder.Services.AddTransient(typeof(IDatabaseSchemaTable), typeof(DatabaseSchemaTable));
            hostApplicationBuilder.Services.AddTransient(typeof(global::Foundation.Models.Core.EnumModels.DataStatus));
            hostApplicationBuilder.Services.AddTransient(typeof(IDataStatus), typeof(global::Foundation.Models.Core.EnumModels.DataStatus));
            hostApplicationBuilder.Services.AddTransient(typeof(DataStatusProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IDataStatusProcess), typeof(DataStatusProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(DataStatusRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IDataStatusRepository), typeof(DataStatusRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(DataStatusViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IDataStatusViewModel), typeof(DataStatusViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(global::Foundation.Models.Core.EnumModels.DatePeriod));
            hostApplicationBuilder.Services.AddTransient(typeof(IDatePeriod), typeof(global::Foundation.Models.Core.EnumModels.DatePeriod));
            hostApplicationBuilder.Services.AddTransient(typeof(DatePeriodProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IDatePeriodProcess), typeof(DatePeriodProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(DatePeriodRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IDatePeriodRepository), typeof(DatePeriodRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(DatePeriodViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IDatePeriodViewModel), typeof(DatePeriodViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(DateTimeService));
            hostApplicationBuilder.Services.AddTransient(typeof(IDateTimeService), typeof(DateTimeService));
            hostApplicationBuilder.Services.AddTransient(typeof(DbSchemaTableRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IDatabaseSchemaTableDataAccess), typeof(DbSchemaTableRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(Department));
            hostApplicationBuilder.Services.AddTransient(typeof(IDepartment), typeof(Department));
            hostApplicationBuilder.Services.AddTransient(typeof(DepartmentProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IDepartmentProcess), typeof(DepartmentProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(DepartmentRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IDepartmentRepository), typeof(DepartmentRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(DepartmentViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IDepartmentViewModel), typeof(DepartmentViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(DialogService));
            hostApplicationBuilder.Services.AddTransient(typeof(IDialogService), typeof(DialogService));
            hostApplicationBuilder.Services.AddTransient(typeof(EmailApi));
            hostApplicationBuilder.Services.AddTransient(typeof(IEmailApi), typeof(EmailApi));
            hostApplicationBuilder.Services.AddTransient(typeof(EmailApi));
            hostApplicationBuilder.Services.AddTransient(typeof(IRemoteServiceApi), typeof(EmailApi));
            hostApplicationBuilder.Services.AddTransient(typeof(EncryptionService));
            hostApplicationBuilder.Services.AddTransient(typeof(IEncryptionService), typeof(EncryptionService));
            hostApplicationBuilder.Services.AddTransient(typeof(global::Foundation.Models.Core.EnumModels.EntityStatus));
            hostApplicationBuilder.Services.AddTransient(typeof(IEntityStatus), typeof(global::Foundation.Models.Core.EnumModels.EntityStatus));
            hostApplicationBuilder.Services.AddTransient(typeof(EntityStatusProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IEntityStatusProcess), typeof(EntityStatusProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(EntityStatusRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IEntityStatusRepository), typeof(EntityStatusRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(EntityStatusViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IEntityStatusViewModel), typeof(EntityStatusViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(EventLog));
            hostApplicationBuilder.Services.AddTransient(typeof(IEventLog), typeof(EventLog));
            hostApplicationBuilder.Services.AddTransient(typeof(EventLogApplication));
            hostApplicationBuilder.Services.AddTransient(typeof(IEventLogApplication), typeof(EventLogApplication));
            hostApplicationBuilder.Services.AddTransient(typeof(EventLogApplicationProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IEventLogApplicationProcess), typeof(EventLogApplicationProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(EventLogApplicationRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IEventLogApplicationRepository), typeof(EventLogApplicationRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(EventLogApplicationViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IEventLogApplicationViewModel), typeof(EventLogApplicationViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(EventLogAttachment));
            hostApplicationBuilder.Services.AddTransient(typeof(IEventLogAttachment), typeof(EventLogAttachment));
            hostApplicationBuilder.Services.AddTransient(typeof(EventLogAttachmentProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IEventLogAttachmentProcess), typeof(EventLogAttachmentProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(EventLogAttachmentRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IEventLogAttachmentRepository), typeof(EventLogAttachmentRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(EventLogAttachmentViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IEventLogAttachmentViewModel), typeof(EventLogAttachmentViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(EventLogProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IEventLogProcess), typeof(EventLogProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(EventLogRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IEventLogRepository), typeof(EventLogRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(EventLogViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IEventLogViewModel), typeof(EventLogViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(FileService));
            hostApplicationBuilder.Services.AddTransient(typeof(IFileApi), typeof(FileService));
            hostApplicationBuilder.Services.AddTransient(typeof(FileService));
            hostApplicationBuilder.Services.AddTransient(typeof(IRemoteServiceApi), typeof(FileService));
            hostApplicationBuilder.Services.AddTransient(typeof(FileTransferService));
            hostApplicationBuilder.Services.AddTransient(typeof(IFileTransferService), typeof(FileTransferService));
            hostApplicationBuilder.Services.AddTransient(typeof(FileTransferSettings));
            hostApplicationBuilder.Services.AddTransient(typeof(IFileTransferSettings), typeof(FileTransferSettings));
            hostApplicationBuilder.Services.AddTransient(typeof(FtpApi));
            hostApplicationBuilder.Services.AddTransient(typeof(IFtpApi), typeof(FtpApi));
            hostApplicationBuilder.Services.AddTransient(typeof(FtpApi));
            hostApplicationBuilder.Services.AddTransient(typeof(IRemoteServiceApi), typeof(FtpApi));
            hostApplicationBuilder.Services.AddTransient(typeof(GridColumnDefinition));
            hostApplicationBuilder.Services.AddTransient(typeof(IGridColumnDefinition), typeof(GridColumnDefinition));
            hostApplicationBuilder.Services.AddTransient(typeof(HashingService));
            hostApplicationBuilder.Services.AddTransient(typeof(IHashingService), typeof(HashingService));
            hostApplicationBuilder.Services.AddTransient(typeof(HeartbeatResult));
            hostApplicationBuilder.Services.AddTransient(typeof(IHeartbeatResult), typeof(HeartbeatResult));
            hostApplicationBuilder.Services.AddTransient(typeof(HttpApi));
            hostApplicationBuilder.Services.AddTransient(typeof(IHttpApi), typeof(HttpApi));
            hostApplicationBuilder.Services.AddTransient(typeof(HttpApi));
            hostApplicationBuilder.Services.AddTransient(typeof(IRemoteServiceApi), typeof(HttpApi));
            hostApplicationBuilder.Services.AddTransient(typeof(ImageType));
            hostApplicationBuilder.Services.AddTransient(typeof(IImageType), typeof(ImageType));
            hostApplicationBuilder.Services.AddTransient(typeof(ImageTypeProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IImageTypeProcess), typeof(ImageTypeProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ImageTypeRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IImageTypeRepository), typeof(ImageTypeRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ImageTypeViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IImageTypeViewModel), typeof(ImageTypeViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ImportExportControl));
            hostApplicationBuilder.Services.AddTransient(typeof(IImportExportControl), typeof(ImportExportControl));
            hostApplicationBuilder.Services.AddTransient(typeof(ImportExportControlProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IImportExportControlProcess), typeof(ImportExportControlProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ImportExportControlRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IImportExportControlRepository), typeof(ImportExportControlRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ImportExportControlViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IImportExportControlViewModel), typeof(ImportExportControlViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(Language));
            hostApplicationBuilder.Services.AddTransient(typeof(ILanguage), typeof(Language));
            hostApplicationBuilder.Services.AddTransient(typeof(LanguageProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ILanguageProcess), typeof(LanguageProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(LanguageRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ILanguageRepository), typeof(LanguageRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(LanguageViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ILanguageViewModel), typeof(LanguageViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(LdapInjectionIdentifier));
            hostApplicationBuilder.Services.AddTransient(typeof(ILdapInjectionIdentifier), typeof(LdapInjectionIdentifier));
            hostApplicationBuilder.Services.AddTransient(typeof(LdapInjectionIdentifier));
            hostApplicationBuilder.Services.AddTransient(typeof(IInjectionIdentifier), typeof(LdapInjectionIdentifier));
            hostApplicationBuilder.Services.AddTransient(typeof(LogDataProvider));
            hostApplicationBuilder.Services.AddTransient(typeof(ILogDataProvider), typeof(LogDataProvider));
            hostApplicationBuilder.Services.AddTransient(typeof(LoggedOnUser));
            hostApplicationBuilder.Services.AddTransient(typeof(ILoggedOnUser), typeof(LoggedOnUser));
            hostApplicationBuilder.Services.AddTransient(typeof(LoggedOnUserProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ILoggedOnUserProcess), typeof(LoggedOnUserProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(LoggedOnUserRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ILoggedOnUserRepository), typeof(LoggedOnUserRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(LoggedOnUserViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ILoggedOnUserViewModel), typeof(LoggedOnUserViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(LoggingService));
            hostApplicationBuilder.Services.AddTransient(typeof(ILoggingService), typeof(LoggingService));
            hostApplicationBuilder.Services.AddTransient(typeof(global::Foundation.Models.Log.EnumModels.LogSeverity));
            hostApplicationBuilder.Services.AddTransient(typeof(ILogSeverity), typeof(global::Foundation.Models.Log.EnumModels.LogSeverity));
            hostApplicationBuilder.Services.AddTransient(typeof(LogSeverityProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ILogSeverityProcess), typeof(LogSeverityProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(LogSeverityRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ILogSeverityRepository), typeof(LogSeverityRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(LogSeverityViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ILogSeverityViewModel), typeof(LogSeverityViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(MailAttachment));
            hostApplicationBuilder.Services.AddTransient(typeof(IMailAttachment), typeof(MailAttachment));
            hostApplicationBuilder.Services.AddTransient(typeof(MailMessage));
            hostApplicationBuilder.Services.AddTransient(typeof(IMailMessage), typeof(MailMessage));
            hostApplicationBuilder.Services.AddTransient(typeof(MailWrapper));
            hostApplicationBuilder.Services.AddTransient(typeof(IMailWrapper), typeof(MailWrapper));
            hostApplicationBuilder.Services.AddTransient(typeof(MainApplicationProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IMainApplicationProcess), typeof(MainApplicationProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(MainWindowForm));
            hostApplicationBuilder.Services.AddTransient(typeof(IMainWindowForm), typeof(MainWindowForm));
            hostApplicationBuilder.Services.AddTransient(typeof(MainWindowForm));
            hostApplicationBuilder.Services.AddTransient(typeof(IViewForm), typeof(MainWindowForm));
            hostApplicationBuilder.Services.AddTransient(typeof(global::Foundation.ViewModels.Main.MainWindowViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IMainWindowViewModel), typeof(global::Foundation.ViewModels.Main.MainWindowViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(MenuItem));
            hostApplicationBuilder.Services.AddTransient(typeof(IMenuItem), typeof(MenuItem));
            hostApplicationBuilder.Services.AddTransient(typeof(MenuItemProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IMenuItemProcess), typeof(MenuItemProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(MenuItemRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IMenuItemRepository), typeof(MenuItemRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(MenuItemViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IMenuItemViewModel), typeof(MenuItemViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(MessageBoxSettings));
            hostApplicationBuilder.Services.AddTransient(typeof(IMessageBoxSettings), typeof(MessageBoxSettings));
            hostApplicationBuilder.Services.AddTransient(typeof(MockFoundationModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IMockFoundationModel), typeof(MockFoundationModel));
            hostApplicationBuilder.Services.AddTransient(typeof(MockFoundationModelProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IMockFoundationModelProcess), typeof(MockFoundationModelProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(MockFoundationModelProcess2));
            hostApplicationBuilder.Services.AddTransient(typeof(IMockFoundationModelProcess2), typeof(MockFoundationModelProcess2));
            hostApplicationBuilder.Services.AddTransient(typeof(MockFoundationModelRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IMockFoundationModelRepository), typeof(MockFoundationModelRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(MouseBusyCursor));
            hostApplicationBuilder.Services.AddTransient(typeof(IMouseCursor), typeof(MouseBusyCursor));
            hostApplicationBuilder.Services.AddTransient(typeof(MqApi));
            hostApplicationBuilder.Services.AddTransient(typeof(IMqApi), typeof(MqApi));
            hostApplicationBuilder.Services.AddTransient(typeof(MqApi));
            hostApplicationBuilder.Services.AddTransient(typeof(IRemoteServiceApi), typeof(MqApi));
            hostApplicationBuilder.Services.AddTransient(typeof(MultipleInstance1));
            hostApplicationBuilder.Services.AddTransient(typeof(IMultipleInstances), typeof(MultipleInstance1));
            hostApplicationBuilder.Services.AddTransient(typeof(MultipleInstance1));
            hostApplicationBuilder.Services.AddTransient(typeof(IInstance1), typeof(MultipleInstance1));
            hostApplicationBuilder.Services.AddTransient(typeof(MultipleInstance2));
            hostApplicationBuilder.Services.AddTransient(typeof(IMultipleInstances), typeof(MultipleInstance2));
            hostApplicationBuilder.Services.AddTransient(typeof(MultipleInstance2));
            hostApplicationBuilder.Services.AddTransient(typeof(IInstance2), typeof(MultipleInstance2));
            hostApplicationBuilder.Services.AddTransient(typeof(MyService));
            hostApplicationBuilder.Services.AddTransient(typeof(IMyService), typeof(MyService));
            hostApplicationBuilder.Services.AddTransient(typeof(NationalRegion));
            hostApplicationBuilder.Services.AddTransient(typeof(INationalRegion), typeof(NationalRegion));
            hostApplicationBuilder.Services.AddTransient(typeof(NationalRegionProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(INationalRegionProcess), typeof(NationalRegionProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(NationalRegionRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(INationalRegionRepository), typeof(NationalRegionRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(NationalRegionViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(INationalRegionViewModel), typeof(NationalRegionViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(NonWorkingDay));
            hostApplicationBuilder.Services.AddTransient(typeof(INonWorkingDay), typeof(NonWorkingDay));
            hostApplicationBuilder.Services.AddTransient(typeof(NonWorkingDayProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(INonWorkingDayProcess), typeof(NonWorkingDayProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(NonWorkingDayRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(INonWorkingDayRepository), typeof(NonWorkingDayRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(NonWorkingDayViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(INonWorkingDayViewModel), typeof(NonWorkingDayViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(Office));
            hostApplicationBuilder.Services.AddTransient(typeof(IOffice), typeof(Office));
            hostApplicationBuilder.Services.AddTransient(typeof(OfficeProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IOfficeProcess), typeof(OfficeProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(OfficeRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IOfficeRepository), typeof(OfficeRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(OfficeViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IOfficeViewModel), typeof(OfficeViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(OfficeWeekCalendar));
            hostApplicationBuilder.Services.AddTransient(typeof(IOfficeWeekCalendar), typeof(OfficeWeekCalendar));
            hostApplicationBuilder.Services.AddTransient(typeof(OfficeWeekCalendarProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IOfficeWeekCalendarProcess), typeof(OfficeWeekCalendarProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(OfficeWeekCalendarRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IOfficeWeekCalendarRepository), typeof(OfficeWeekCalendarRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(OfficeWeekCalendarViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IOfficeWeekCalendarViewModel), typeof(OfficeWeekCalendarViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(OpenFolderDialogSettings));
            hostApplicationBuilder.Services.AddTransient(typeof(IOpenFolderDialogSettings), typeof(OpenFolderDialogSettings));
            hostApplicationBuilder.Services.AddTransient(typeof(PasswordGeneratorService));
            hostApplicationBuilder.Services.AddTransient(typeof(IPasswordGeneratorService), typeof(PasswordGeneratorService));
            hostApplicationBuilder.Services.AddTransient(typeof(PermissionMatrix));
            hostApplicationBuilder.Services.AddTransient(typeof(IPermissionMatrix), typeof(PermissionMatrix));
            hostApplicationBuilder.Services.AddTransient(typeof(PermissionMatrixProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IPermissionMatrixProcess), typeof(PermissionMatrixProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(PermissionMatrixRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IPermissionMatrixRepository), typeof(PermissionMatrixRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(PermissionMatrixViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IPermissionMatrixViewModel), typeof(PermissionMatrixViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(RandomService));
            hostApplicationBuilder.Services.AddTransient(typeof(IRandomService), typeof(RandomService));
            hostApplicationBuilder.Services.AddTransient(typeof(ReportGenerator));
            hostApplicationBuilder.Services.AddTransient(typeof(IReportGenerator), typeof(ReportGenerator));
            hostApplicationBuilder.Services.AddTransient(typeof(RestApi));
            hostApplicationBuilder.Services.AddTransient(typeof(IRestApi), typeof(RestApi));
            hostApplicationBuilder.Services.AddTransient(typeof(RestApi));
            hostApplicationBuilder.Services.AddTransient(typeof(IRemoteServiceApi), typeof(RestApi));
            hostApplicationBuilder.Services.AddTransient(typeof(Role));
            hostApplicationBuilder.Services.AddTransient(typeof(IRole), typeof(Role));
            hostApplicationBuilder.Services.AddTransient(typeof(RoleProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IRoleProcess), typeof(RoleProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(RoleRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IRoleRepository), typeof(RoleRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(RoleViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IRoleViewModel), typeof(RoleViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(RunTimeEnvironmentSettings));
            hostApplicationBuilder.Services.AddTransient(typeof(IRunTimeEnvironmentSettings), typeof(RunTimeEnvironmentSettings));
            hostApplicationBuilder.Services.AddTransient(typeof(SaveFileDialogSettings));
            hostApplicationBuilder.Services.AddTransient(typeof(ISaveFileDialogSettings), typeof(SaveFileDialogSettings));
            hostApplicationBuilder.Services.AddTransient(typeof(ScheduledDataStatus));
            hostApplicationBuilder.Services.AddTransient(typeof(IScheduledDataStatus), typeof(ScheduledDataStatus));
            hostApplicationBuilder.Services.AddTransient(typeof(ScheduledDataStatusProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IScheduledDataStatusProcess), typeof(ScheduledDataStatusProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ScheduledDataStatusRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IScheduledDataStatusRepository), typeof(ScheduledDataStatusRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ScheduledDataStatusViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IScheduledDataStatusViewModel), typeof(ScheduledDataStatusViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ScheduledJob));
            hostApplicationBuilder.Services.AddTransient(typeof(IScheduledJob), typeof(ScheduledJob));
            hostApplicationBuilder.Services.AddTransient(typeof(ScheduledJobProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IScheduledJobProcess), typeof(ScheduledJobProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ScheduledJobRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IScheduledJobRepository), typeof(ScheduledJobRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ScheduledJobViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IScheduledJobViewModel), typeof(ScheduledJobViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(global::Foundation.Models.Core.EnumModels.ScheduleInterval));
            hostApplicationBuilder.Services.AddTransient(typeof(IScheduleInterval), typeof(global::Foundation.Models.Core.EnumModels.ScheduleInterval));
            hostApplicationBuilder.Services.AddTransient(typeof(ScheduleIntervalMultiplierMatrix));
            hostApplicationBuilder.Services.AddTransient(typeof(IScheduleIntervalMultiplierMatrix), typeof(ScheduleIntervalMultiplierMatrix));
            hostApplicationBuilder.Services.AddTransient(typeof(ScheduleIntervalMultiplierMatrixProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IScheduleIntervalMultiplierMatrixProcess), typeof(ScheduleIntervalMultiplierMatrixProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ScheduleIntervalMultiplierMatrixRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IScheduleIntervalMultiplierMatrixRepository), typeof(ScheduleIntervalMultiplierMatrixRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ScheduleIntervalMultiplierMatrixViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IScheduleIntervalMultiplierMatrixViewModel), typeof(ScheduleIntervalMultiplierMatrixViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ScheduleIntervalProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IScheduleIntervalProcess), typeof(ScheduleIntervalProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ScheduleIntervalRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IScheduleIntervalRepository), typeof(ScheduleIntervalRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ScheduleIntervalViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IScheduleIntervalViewModel), typeof(ScheduleIntervalViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(SchemaDataProvider));
            hostApplicationBuilder.Services.AddTransient(typeof(ISchemaDataProvider), typeof(SchemaDataProvider));
            hostApplicationBuilder.Services.AddTransient(typeof(SecurityDataProvider));
            hostApplicationBuilder.Services.AddTransient(typeof(ISecurityDataProvider), typeof(SecurityDataProvider));
            hostApplicationBuilder.Services.AddTransient(typeof(SequenceGenerator));
            hostApplicationBuilder.Services.AddTransient(typeof(ISequenceGenerator), typeof(SequenceGenerator));
            hostApplicationBuilder.Services.AddTransient(typeof(SequenceGeneratorProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ISequenceGeneratorProcess), typeof(SequenceGeneratorProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(SequenceGeneratorRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ISequenceGeneratorRepository), typeof(SequenceGeneratorRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(SequenceGeneratorService));
            hostApplicationBuilder.Services.AddTransient(typeof(ISequenceGeneratorService), typeof(SequenceGeneratorService));
            hostApplicationBuilder.Services.AddTransient(typeof(ServiceControlWrapper));
            hostApplicationBuilder.Services.AddTransient(typeof(IServiceControlWrapper), typeof(ServiceControlWrapper));
            hostApplicationBuilder.Services.AddTransient(typeof(SpreadsheetGenerator));
            hostApplicationBuilder.Services.AddTransient(typeof(ISpreadsheetGenerator), typeof(SpreadsheetGenerator));
            hostApplicationBuilder.Services.AddTransient(typeof(SqlInjectionIdentifier));
            hostApplicationBuilder.Services.AddTransient(typeof(ISqlInjectionIdentifier), typeof(SqlInjectionIdentifier));
            hostApplicationBuilder.Services.AddTransient(typeof(SqlInjectionIdentifier));
            hostApplicationBuilder.Services.AddTransient(typeof(IInjectionIdentifier), typeof(SqlInjectionIdentifier));
            hostApplicationBuilder.Services.AddTransient(typeof(StagingDataProvider));
            hostApplicationBuilder.Services.AddTransient(typeof(IStagingDataProvider), typeof(StagingDataProvider));
            hostApplicationBuilder.Services.AddTransient(typeof(Status));
            hostApplicationBuilder.Services.AddTransient(typeof(IStatus), typeof(Status));
            hostApplicationBuilder.Services.AddTransient(typeof(StatusProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IStatusProcess), typeof(StatusProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(StatusRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IStatusRepository), typeof(StatusRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(StatusViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IStatusViewModel), typeof(StatusViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(SystemConfigurationService));
            hostApplicationBuilder.Services.AddTransient(typeof(ISystemConfigurationService), typeof(SystemConfigurationService));
            hostApplicationBuilder.Services.AddTransient(typeof(global::Foundation.Models.Core.EnumModels.TaskStatus));
            hostApplicationBuilder.Services.AddTransient(typeof(ITaskStatus), typeof(global::Foundation.Models.Core.EnumModels.TaskStatus));
            hostApplicationBuilder.Services.AddTransient(typeof(TaskStatusProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ITaskStatusProcess), typeof(TaskStatusProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(TaskStatusRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ITaskStatusRepository), typeof(TaskStatusRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(TaskStatusViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ITaskStatusViewModel), typeof(TaskStatusViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(TestFormViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ITestFormViewModel), typeof(TestFormViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(TestSupportService));
            hostApplicationBuilder.Services.AddTransient(typeof(ITestSupportService), typeof(TestSupportService));
            hostApplicationBuilder.Services.AddTransient(typeof(global::Foundation.Models.Core.TimeZone));
            hostApplicationBuilder.Services.AddTransient(typeof(ITimeZone), typeof(global::Foundation.Models.Core.TimeZone));
            hostApplicationBuilder.Services.AddTransient(typeof(TimeZoneProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(ITimeZoneProcess), typeof(TimeZoneProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(TimeZoneRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(ITimeZoneRepository), typeof(TimeZoneRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(TimeZoneViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(ITimeZoneViewModel), typeof(TimeZoneViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(TransientOperation));
            hostApplicationBuilder.Services.AddTransient(typeof(ITransientOperation), typeof(TransientOperation));
            hostApplicationBuilder.Services.AddTransient(typeof(UnitTestingDataProvider));
            hostApplicationBuilder.Services.AddTransient(typeof(IUnitTestingDataProvider), typeof(UnitTestingDataProvider));
            hostApplicationBuilder.Services.AddTransient(typeof(UnitTestingDataProvider));
            hostApplicationBuilder.Services.AddTransient(typeof(IDataProvider), typeof(UnitTestingDataProvider));
            hostApplicationBuilder.Services.AddTransient(typeof(UserProfile));
            hostApplicationBuilder.Services.AddTransient(typeof(IUserProfile), typeof(UserProfile));
            hostApplicationBuilder.Services.AddTransient(typeof(UserProfileProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IUserProfileProcess), typeof(UserProfileProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(UserProfileRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IUserProfileRepository), typeof(UserProfileRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(UserProfileViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IUserProfileViewModel), typeof(UserProfileViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(WorkflowProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IWorkflowProcess), typeof(WorkflowProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(WorldRegion));
            hostApplicationBuilder.Services.AddTransient(typeof(IWorldRegion), typeof(WorldRegion));
            hostApplicationBuilder.Services.AddTransient(typeof(WorldRegionProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(IWorldRegionProcess), typeof(WorldRegionProcess));
            hostApplicationBuilder.Services.AddTransient(typeof(WorldRegionRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(IWorldRegionRepository), typeof(WorldRegionRepository));
            hostApplicationBuilder.Services.AddTransient(typeof(WorldRegionViewModel));
            hostApplicationBuilder.Services.AddTransient(typeof(IWorldRegionViewModel), typeof(WorldRegionViewModel));
        }
    }
}

/*
Service Type: Foundation.Interfaces.IMenuItem. Implementation Type: Foundation.Models.App.MenuItem
Service Type: Foundation.Tests.Unit.Support.IInstance1. Implementation Type: Foundation.Tests.Unit.Support.MultipleInstance1
*/