CREATE TABLE [app].[MenuItem] (
    [Id]                         INT             IDENTITY (1, 1) NOT NULL,
    [Timestamp]                  ROWVERSION      NOT NULL,
    [StatusId]                   INT             NOT NULL,
    [CreatedByUserProfileId]     INT             NOT NULL,
    [LastUpdatedByUserProfileId] INT             NOT NULL,
    [CreatedOn]                  DATETIME        NOT NULL,
    [LastUpdatedOn]              DATETIME        NOT NULL,
    [ValidFrom]                  DATETIME        NOT NULL,
    [ValidTo]                    DATETIME        NOT NULL,
    [ApplicationId]              INT             NULL,
    [ParentMenuItemId]           INT             NULL,
    [Name]                       NVARCHAR (250)  NULL,
    [Caption]                    NVARCHAR (250)  NULL,
    [ControllerAssembly]         NVARCHAR (250)  NULL,
    [ControllerType]             NVARCHAR (250)  NULL,
    [ViewAssembly]               NVARCHAR (250)  NULL,
    [ViewType]                   NVARCHAR (250)  NULL,
    [HelpText]                   NVARCHAR (MAX)  NULL,
    [MultiInstance]              BIT             NULL,
    [ShowInTab]                  BIT             NULL,
    [Icon]                       VARBINARY (MAX) NULL,
    [DisplayOrder]               INT             NULL,
    CONSTRAINT [PK_APP_MenuItem] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MenuItem_Application] FOREIGN KEY ([ApplicationId]) REFERENCES [sec].[Application] ([Id]),
    CONSTRAINT [FK_MenuItem_CreatedByUserProfile] FOREIGN KEY ([CreatedByUserProfileId]) REFERENCES [sec].[UserProfile] ([Id]),
    CONSTRAINT [FK_MenuItem_LastUpdatedByUserProfile] FOREIGN KEY ([LastUpdatedByUserProfileId]) REFERENCES [sec].[UserProfile] ([Id]),
    CONSTRAINT [FK_MenuItem_MenuItem] FOREIGN KEY ([ParentMenuItemId]) REFERENCES [app].[MenuItem] ([Id]),
    CONSTRAINT [FK_MenuItem_Status] FOREIGN KEY ([StatusId]) REFERENCES [core].[Status] ([Id])
);

